### ISSUE TITLE
asking for the cuda OOM questions

### ISSUE THREAD

**Issue by gonghouyu** [ZhixiuYe/HSCRF-pytorch#10]
I run the code on a Chinese ner train data(around 70 thousand sentences), and I got the OMM error:
 - Tot it 541 (epoch 0): 0it [00:00, ?it/s]THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 179, in <module>
    loss.backward()
  File "/usr/lib64/python2.7/site-packages/torch/autograd/variable.py", line 156, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/usr/lib64/python2.7/site-packages/torch/autograd/__init__.py", line 98, in backward
    variables, grad_variables, retain_graph)
  File "/usr/lib64/python2.7/site-packages/torch/autograd/function.py", line 91, in apply
    return self._forward_cls.backward(self, *args)
  File "/usr/lib64/python2.7/site-packages/torch/autograd/function.py", line 194, in wrapper
    outputs = fn(ctx, *tensor_args)
  File "/usr/lib64/python2.7/site-packages/torch/nn/_functions/thnn/sparse.py", line 80, in backward
    grad_weight = grad_output.new(ctx._weight_size).zero_()
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:66 
I have set the batch_size to 10 and 128, and both of them result in the error shown above. Could any one give me some advise to solve it?

**Comment by ZhixiuYe** [comment]
Maybe you can try a smaller batch_size, like 2 or 5.
